### ISSUE TITLE
Gameplay/Major/Clipping wall images when they appear on the bottom part of the battlefield

### ISSUE THREAD

**Issue by lgouvin** [cbb692/wizardsNStuff#16]

**Comment by c4llmeco4ch** [comment]
Only applies to walls and slashes, too close to camera.

**Comment by c4llmeco4ch** [comment]
Try rotating wall 45º on x-axis and lower from 3 to 2 on y-axis, and translate back 2 on the z-axis, unless -2 makes z value greater than -3, in which case make it -3. Should fix problem?

**Comment by c4llmeco4ch** [comment]
Fixed on April 17 build
