### ISSUE TITLE
Gameplay/Minor/Characters shouldn't keep running while casting

### ISSUE THREAD

**Issue by lgouvin** [cbb692/wizardsNStuff#18]

**Comment by c4llmeco4ch** [comment]
Fixed 3-26-15 Build

**Comment by c4llmeco4ch** [comment]
Steps to repro:

Move
Cast spell while moving
Observe

If you are not moving while you are casting, you will not see the bug even if you try to move after casting.

**Comment by c4llmeco4ch** [comment]
Fixed 4-2-15 Build
