### ISSUE TITLE
Gameplay/Minor/Walls should last longer

### ISSUE THREAD

**Issue by lgouvin** [cbb692/wizardsNStuff#20]

**Comment by c4llmeco4ch** [comment]
Mostly on Konstantine to toss me values, but yea

**Comment by c4llmeco4ch** [comment]
Changed algorithm for dealing with time, need values from Konstantine on new var Duration.

**Comment by c4llmeco4ch** [comment]
@Konstantanium , playtest and see if the new values look solid to you. If so, close this.

**Comment by c4llmeco4ch** [comment]
Fixed 4-2-15
